
import {
  LayoutDashboard, Package, ShoppingCart, TrendingUp, Settings, Bell,
  Search, Plus, Wallet, BarChart3, AlertCircle, Sparkles, Image,
  Store, Eye, EyeOff, ShieldCheck, CheckCircle2, Lock,
  RefreshCcw, ChevronRight, Filter, AlertTriangle, ArrowUpRight, ArrowDownLeft,
  Lightbulb, Trash2, Edit2, X, MoreVertical, LogOut, Check,
  Zap, Cpu, Globe, Mail, User, Bot, Send, DollarSign,
  MapPin, Truck, Warehouse, History, CreditCard, ExternalLink,
  Tag, Info, XCircle, ScanLine, Camera, Monitor, Smartphone, Battery,
  Loader2, BadgeCheck, MessageCircle, MessageSquare, HelpCircle,
  ArrowRight, ArrowLeft
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Package,
  Cart: ShoppingCart,
  TrendingUp,
  Settings,
  Bell,
  Search,
  Plus,
  Wallet,
  Chart: BarChart3,
  Alert: AlertCircle,
  Sparkles,
  Image,
  Store,
  Eye,
  EyeOff,
  Shield: ShieldCheck,
  CheckCircle: CheckCircle2,
  Lock,
  Refresh: RefreshCcw,
  ChevronRight,
  Filter,
  Warning: AlertTriangle,
  ArrowUpRight,
  ArrowDownLeft,
  Lightbulb,
  Trash: Trash2,
  Edit: Edit2,
  X,
  More: MoreVertical,
  LogOut,
  Check,
  Zap,
  Cpu,
  Globe,
  Mail,
  User,
  Bot,
  Send,
  Dollar: DollarSign,
  MapPin,
  Truck,
  Warehouse,
  History,
  CreditCard,
  ExternalLink,
  Tag,
  Info,
  XCircle,
  Scan: ScanLine,
  Camera,
  Monitor,
  Phone: Smartphone,
  Battery,
  Loader: Loader2,
  Badge: BadgeCheck,
  Message: MessageCircle,
  Chat: MessageSquare,
  Help: HelpCircle,
  ArrowRight,
  ArrowLeft
};
